// ADMIN
export const CREATE_USER = "CREATE_USER";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const GET_AGENTS = "GET_AGENTS";
export const GET_AGENT_DETAILS = "GET_AGENT_DETAILS";
export const SET_STORE_LINK = "SET_STORE_LINK";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// SHARED
export const GET_SUBSCRIBERS = "GET_SUBSCRIBERS";
export const GET_SUBSCRIBER = "GET_SUBSCRIBER";
export const GET_GURUJIS = "GET_GURUJIS";
export const GET_GURUJI_DETAILS = "GET_GURUJI_DETAILS";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const CLEAR_ERROR_RESPONSE_STATE = "CLEAR_ERROR_RESPONSE_STATE";
export const GET_PLATFORM_STORE_LINK = "GET_PLATFORM_STORE_LINK";
export const SHARED_ERROR = "SHARED_ERROR";

// USER
export const SUBSCRIBE_TO_GURUJI = "SUBSCRIBE_TO_GURUJI";
export const GET_SUBSCRIBED_CONTENT = "GET_SUBSCRIBED_CONTENT";
export const USER_ERROR = "USER_ERROR";

// GURUJI
export const UPLOAD_CONTENT = "UPLOAD_CONTENT";
export const UPDATE_PERSONAL_STORE = "UPDATE_PERSONAL_STORE";
export const GURUJI_ERROR = "GURUJI_ERROR";